name: dart_backend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bcrypt: ^1.1.3
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  json_annotation: ^4.9.0
  path: ^1.9.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  sqflite_common_ffi_web: ^1.0.0
  toastification: ^0.0.2
  calendar_timeline: ^1.1.3
  intl: ^0.19.0
  time_picker_spinner_pop_up: ^2.0.0
  dropdown_button2: ^2.3.9
  flex_color_picker: ^3.7.1
  flutter_local_notifications: ^19.4.0
  flutter_native_timezone: ^2.0.0
  get_storage: ^2.1.1
  # shadcn_ui: ^0.28.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - .env
